/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0061a4",
        "primary-container": "#2196f3",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#9ecaff",
        "on-primary": "#ffffff",
        "on-primary-container": "#002c4f",
        "on-primary-fixed": "#001d36",
        "on-primary-fixed-variant": "#00497d",
        "secondary": "#006398",
        "secondary-container": "#6cbdfe",
        "secondary-fixed": "#cde5ff",
        "secondary-fixed-dim": "#94ccff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004b75",
        "on-secondary-fixed": "#001d32",
        "on-secondary-fixed-variant": "#004b74",
        "tertiary": "#904d00",
        "tertiary-container": "#db7900",
        "tertiary-fixed": "#ffdcc2",
        "tertiary-fixed-dim": "#ffb77b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#452200",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#6d3900",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#0061a4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#404752",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "outline": "#707883",
        "outline-variant": "#bfc7d4",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#9ecaff",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
};
